version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - neo4j
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: archelyst
      POSTGRES_USER: archelyst
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    
  neo4j:
    image: neo4j:5.15
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc","gds"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

  celery:
    build: .
    command: celery -A app.workers.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app

  celery-beat:
    build: .
    command: celery -A app.workers.celery_app beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./app:/app/app
    environment:
      - PYTHONPATH=/app

volumes:
  postgres_data:
  redis_data:
  neo4j_data:
  neo4j_logs: